# -*- coding: utf-8 -*-
"""mcBootstrap.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rmS95WgWgLrUMNgIbzG8mDdxcoVs7vei
"""

import time
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import pearsonr

law = pd.read_csv('law.csv')
start_time = time.process_time()
j = len(law["LSAT"])
B = 40000
mc_correlations = np.zeros(B)

for i in range(B):
  mc_sample = np.random.choice(j, size=j, replace=True)
  law_sample = law.iloc[mc_sample]
  mc_correlations[i] = pearsonr(law_sample["LSAT"], law_sample["GPA"])[0]

print(time.process_time() - start_time)

boot_data = np.column_stack((mc_correlations, np.ones(B)))
df_boot_data = pd.DataFrame(boot_data, columns=["mc_correlations", "const"])

plt.hist(df_boot_data["mc_correlations"], bins=np.arange(-1, 1, 0.01))
plt.axvline(x=pearsonr(law["LSAT"], law["GPA"])[0], color="red")
plt.xlabel("Correlation")
plt.ylabel("Count")
plt.title("Monte Carlo Bootstrap Distribution")
plt.show()